feat: add command for showing AST and named AST
returntocorp/semgrep-vscode pull request #40
Opened 2023-05-19 01:23 UTC by brandonspark

## What:
This PR tries to add in a `showAst` and `showAstNamed` command, which will scan the currently opened file, and output the pretty-printed AST in a Yojson format.

## Why:
This would be really helpful for people developing Semgrep, or people who are writing rules, I reckon.

## How:
I added in the commands, similarly to the other ones included. I followed `rust-analyzer`, for the most part. I didn't touch anything related to actually interpreting the output that is generated from the command, especially for presenting it within the UI, but I have vague hopes that the output will end up somewhere.

## Test plan:
I have no idea how to test this.

### Security

- [ ] Change has security implications (if so, ping the security team)

2023-05-23 16:53 UTC, ajbt200128 requested changes
So the main thing missing here is actually showing the output somewhere. I think there are 3 main ways of doing this I've seen (in order of amount of work):

1. send over the AST as just formatted text (I think you're doing this now), open a new file to the side of the current and just display it
2. Convert the AST to some sort of JSON (not sure what this would look like) and display it in a [tree view ](https://code.visualstudio.com/api/extension-guides/tree-view), here's what I did for the search demo [branch](https://github.com/returntocorp/semgrep-vscode/tree/austin/search)
3. Do what ocamllabs does, which is custom react [link](https://github.com/ocamllabs/vscode-ocaml-platform/tree/master/astexplorer)

My preference is 2, though I'd be ok with 1. What ocamllabs does is... kind of weird, I don't think it's recommended by Microsoft, and I think the tree view has the same functionality.

To get the highlight text -> show ast functionality you mentioned, you're almost there, you just would add a context menu option [ref](https://code.visualstudio.com/api/ux-guidelines/context-menus) that gets the selection range and then pass that range to the showAst commands (VSCode makes it easy to call commands internally once they're registered), and on the ocaml side, read the file and trim it to that range.

2023-05-23 16:56 UTC, ajbt200128 commented on src/commands.ts
> +    await client.sendRequest(showAst, {
`sendRequest` returns the result of the request, so in your case the AST. this is where you'd want to call some function to show it in the UI

2023-06-21 05:42 UTC, brandonspark commented
@ajbt200128 I added some UI stuff, according to these two sources:
https://github.com/microsoft/vscode-extension-samples/blob/main/contentprovider-sample/src/extension.ts
https://code.visualstudio.com/api/extension-guides/virtual-documents

I wasn't sure of how to turn the Generic AST into a proper JSON value, so right now I'm just going for the text document method. Down to change this later if I figure that out + once I get my bearings on this VS Code thing a bit more.

2023-06-21 05:48 UTC, brandonspark commented
I also... still don't know how to test this locally. Would love to sync about it, if you have time to show me.

2023-06-22 22:40 UTC, ajbt200128 commented on src/commands.ts
> +    const uri = encodeUri(vscode.editor.document.uri);
```suggestion
    const uri = encodeUri(vscode.window.activeEditor.document.uri);
```

2023-06-22 22:41 UTC, ajbt200128 commented on src/commands.ts
> +    const uri = encodeUri(vscode.editor.document.uri);
```suggestion
    const uri = encodeUri(vscode.window.activeEditor.document.uri);
```

2023-06-22 22:43 UTC, ajbt200128 reviewed
I think for the text ast approach using this virtual documents approach makes sense! Overall looks good, we should probably document these commands in the readme

2023-06-24 19:41 UTC, brandonspark commented
https://github.com/returntocorp/semgrep-vscode/assets/49291449/4e2f683a-701a-4759-b213-71397896f9db

2023-07-14 20:44 UTC, ajbt200128 approved these changes
Looks good, added a few nits.

2023-07-14 20:44 UTC, ajbt200128 commented on package.json
> +        "command": "semgrep.showAstNamed",
Can you add a `when` clause and check the minor version here? I'm guessing it'll prolly be minor version 33. See the search command below for how to do that

2023-07-14 20:44 UTC, ajbt200128 commented on src/commands.ts
> +    vscode.window.activeTextEditor!.viewColumn! + 1
Nit: I would add a check here for the active text editor. I know it seems unlikely but a user /may/ run this command without a text editor focused, i.e. they clicked on the sidebar or they're on the welcome page

2023-07-14 20:44 UTC, ajbt200128 commented on src/commands.ts
> +      vscode.window.activeTextEditor?.document.uri || vscode.Uri.parse("")
Same nit here as above, I'd add a check for active editor

2023-08-16 23:51 UTC, brandonspark commented
@ajbt200128 finally got around to this. I verified that no crash happens when running `showAst` with no active window.

2023-08-17 15:57 UTC, merged